// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq4LNrqpQWodHoD9orahL5k51BFDEb-gk',
    appId: '1:740488075405:web:c9d476a99b525119d9aac4',
    messagingSenderId: '740488075405',
    projectId: 'quizqi-2d27b',
    authDomain: 'quizqi-2d27b.firebaseapp.com',
    storageBucket: 'quizqi-2d27b.firebasestorage.app',
    measurementId: 'G-D43C5NK6TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUtdsG7ZQw50hAExCTuwzxkCUCTWowUxE',
    appId: '1:740488075405:android:c9e1a01686af218dd9aac4',
    messagingSenderId: '740488075405',
    projectId: 'quizqi-2d27b',
    storageBucket: 'quizqi-2d27b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRdlVOGCXcY4p-h5JFgZBYcNly52dtVA',
    appId: '1:740488075405:ios:2b4f0ba609396869d9aac4',
    messagingSenderId: '740488075405',
    projectId: 'quizqi-2d27b',
    storageBucket: 'quizqi-2d27b.firebasestorage.app',
    iosBundleId: 'com.parrel.quizbot',
  );
}
